fix: android `CMakeLists.txt` for newer versions of react-native (#74)
* chore: rename android library name

* fix: android CMakeLists.txt

* chore: use java 11 on CI

* chore: attempt to fix android CI

* chore: no verbose makefile and no specific version for android implementations

* chore: verify lint report

* revert: specific version 0.71.6 on android/build.gradle

* chore: android/build/reports/lint-results-debug.xml

diff --git a/.github/workflows/validate-android.yml b/.github/workflows/validate-android.yml
--- a/.github/workflows/validate-android.yml
+++ b/.github/workflows/validate-android.yml
@@ -23,10 +23,10 @@ jobs:
         working-directory: ./android
     steps:
       - uses: actions/checkout@v2
-      - name: Setup JDK 1.8
+      - name: Setup JDK 11
         uses: actions/setup-java@v1
         with:
-          java-version: 1.8
+          java-version: 11
 
       - name: Get yarn cache directory path
         id: yarn-cache-dir-path
@@ -55,11 +55,17 @@ jobs:
             ${{ runner.os }}-gradle-
       - name: Run Gradle Lint
         run: ./gradlew lint --build-cache
-
+      - name: Verify lint report exists
+        run: |
+          ls -R build/reports
+          if [ ! -f "build/reports/lint-results-debug.xml" ]; then
+            echo "Lint report not found!"
+            exit 1
+          fi
       - name: Parse Gradle Lint Report
         uses: yutailang0119/action-android-lint@v1.0.2
         with:
-          xml_path: android/build/reports/lint-results.xml
+          xml_path: android/build/reports/lint-results-debug.xml
   # ktlint:
   #   name: Kotlin Lint
   #   runs-on: ubuntu-latest
